### PR TITLE
Fix issues reported by Coverity

### LINKED ISSUE #28: Invalid comparison in Database::commit_task
`if` statement on line 231 causes following warning:
```
[...] Database.cpp:231:27: warning: result of comparison of constant 18446744073709551615 with expression of type 'uint32_t' (aka 'unsigned int') is always false [-Wtautological-constant-out-of-range-compare]
            if (split_loc == std::string::npos) {
```

### PR DESCRIPTION
**Pull request by icedevml**
fix #28

### CODE REVIEW

File: libursa/Makefile [hunk 1]
```diff
@@ -0,0 +1,976 @@
+# CMAKE generated file: DO NOT EDIT!
```
Comment (msm-code) [inline libursa/Makefile]: :thinking:

Comment (msm-code) [reply libursa/Makefile]: Do we really want to commit that?

File: src/Client.cpp [hunk 2]
```diff
@@ -240,6 +240,13 @@ int main(int argc, char *argv[]) {
...
     }
 
-    UrsaClient client(server_addr, db_command, is_interactive, raw_json);
-    return client.start();
+    try {
+        UrsaClient client(server_addr, db_command, is_interactive, raw_json);
+        client.start();
+    } catch (const zmq::error_t &ex) {
+        spdlog::error("ZeroMQ error: {}", ex.what());
+	return 1;
```
Comment (msm-code) [inline src/Client.cpp]: tabs?
